### ISSUE TITLE
 docs(styleguide): cover how to comment code

### ISSUE THREAD

**Issue by mariocao** [witnet/sheikah#100]
Add section for describing the comment styling that should be followed (e.g. JSDoc).
Include also what should be commented for documentation purposes (e.g. functions, interfaces, enums, and classes).

**Comment by kronolynx** [comment]
I was looking and found:
https://react-styleguidist.js.org/docs/documenting.html
but as we are using typescript
https://blog.cloudflare.com/generating-documentation-for-typescript-projects/

this one seems interesting for generating documentation
http://typedoc.org/guides/doccomments/

**Comment by kronolynx** [comment]
The most common comment convention comes from javascript and is the one we are already following
http://usejsdoc.org/about-getting-started.html

**Comment by aesedepece** [comment]
Is `tslint` enforcing this?
