### ISSUE TITLE
Claiming process UI polish

### ISSUE THREAD

**Issue by Tommytrg** [witnet/sheikah#1002]
Claiming process UI should be discuss in Figma and then apply the changes suggested.

**Comment by aesedepece** [comment]
I'm doing some work on this. Will keep you updated when I have something to show :wink:

**Comment by aesedepece** [comment]
@Tommytrg @gabaldon I forked the claiming process style file into an alternative version, just to try something different and more in line with the Witnet project aesthetics. Please find it in the Witnet project on Figma. It's called "Claiming process — ALT".

**Comment by gabaldon** [comment]
- [ ] Implement disclaimer component

- [ ] Update theme colors and default shadow

- [ ] Change password input

- [ ] Update ```DownloadFile``` component to new style

**Comment by Tommytrg** [comment]
Closed by #1011
