### ISSUE TITLE
All nanowit values are being 0-trimmed on the LSB side

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#1022]
**Description**
The function that transforms nanowit values into strings is removing any zero digit that it founds on the right side of the number, causing transactions and balances to show incorrect readings. 

**How To Reproduce**
- Send 60 nanowits to your wallet. 
- Send 40 nanowits to your wallet.

**Expected behavior**
Your balance should show 100, and the transactions show show 60 and 40.

Instead, the balance shows 1, and the transactions show 6 and 4.

**Comment by Tommytrg** [comment]
Closed by #1025
