### ISSUE TITLE
Token generation event bundle assessment

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#1033]
We need to:
- discuss and decide what to leave as it is, what to put more work on, and what to disable.
- execute it.

**Comment by Tommytrg** [comment]
I suggest hide / remove at least:
- Import wallet from `xprv`. AFAIK this feature is not implemented.
- Data request marketplace. In this case, we could consider let the Marketplace tab disabled in the Sidebar or remove it and don't let the user know about this missing feature. I'm on the side of  remove it completely and keep it simple to avoid mess up users.

**Comment by mariocao** [comment]
For sure there is some code within the wallet to create a wallet from `xprv`. I will take a look :smile:

**Comment by mariocao** [comment]
I just confirmed it! It works!

**Comment by Tommytrg** [comment]
I've opened #1176 to allow import a wallet from `xprv`

Regarding what to show or hide, do you think we should hide something else?

**Comment by Tommytrg** [comment]
As discussed in #1176 we are not going to allow  import wallets from `xprv`. Accordingly, for the time being, we can just hide the Marketplace section.

**Comment by Tommytrg** [comment]
The token generation event date already passed
