### ISSUE TITLE
Disable textarea properties in confirm seed input

### ISSUE THREAD

**Issue by Tommytrg** [witnet/sheikah#1077]
We should fix the confirm seed input to prevent this behavior:

![image](https://user-images.githubusercontent.com/24905681/80575313-aa9a5f00-8a03-11ea-90ed-a0899aed3755.png)

![image](https://user-images.githubusercontent.com/24905681/80575643-344a2c80-8a04-11ea-990c-0cd0c79dbaf1.png)

We need to implement the following features to do so:
- Limit max. number of characters allowed.
- Remove `resize` property.

**Comment by aesedepece** [comment]
Let's take the chance to change to a monotype font and make sure we get 6 words per line.
