### ISSUE TITLE
docs(github): issue templates not being recognized by GitHub

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#111]
Since we moved all docs into `/docs` in #59, GitHub seams to have stopped recognizing the issue templates:

![screenhost](https://screenshotscdn.firefoxusercontent.com/images/a50fad17-1cfc-43d7-b5d3-c938ebf001d6.png)

**Comment by csmoe** [comment]
https://help.github.com/articles/manually-creating-a-single-issue-template-for-your-repository/#adding-an-issue-template
so the templates path might needs to be added manually.

**Comment by aesedepece** [comment]
It seams like GitHub no longer automatically reads templates from `/docs/ISSUE_TEMPLATE/` but only from `/.github/ISSUE_TEMPLATE`.

The legacy URL template injection feature does work ([example]), but that isn't convenient at all.

[example]: https://github.com/witnet/sheikah/issues/new?template=bug_report.md
