### ISSUE TITLE
Wrong scroll behavior with too many addresses

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/sheikah#1125]
There are 5 rows of addresses, but the first one cannot be accessed because it is too far up. The second row is slightly cropped.

![Captura de pantalla de 2020-05-19 16-44-14](https://user-images.githubusercontent.com/44604217/82342801-5b3bc300-99f2-11ea-8f17-1630b3e20eda.png)

Scrolling down works fine.

**Comment by tmpolaczyk** [comment]
Still not fixed to me as of commit 1cf1479d7ebed926a984c28806145eb565f56d24

![Captura de pantalla de 2020-06-01 10-56-36](https://user-images.githubusercontent.com/44604217/83393799-b2c92e00-a3f7-11ea-9d1c-f796f036deab.png)

In the screenshot, the selected address is address 10, address 1 cannot be clicked because it is too far up.

**Comment by Tommytrg** [comment]
Closed by #1160
