### ISSUE TITLE
Having sheikah open disables Ctrl-R in other applications

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/sheikah#1132]
Sheikah attempts to block some key presses to avoid allowing the user to reload the page, for example. This is implemented here:

https://github.com/witnet/sheikah/blob/c0b035a37a9ae5cd29a447e1c523253abdc65d06/src/background.js#L105

According to the electron documentation, 
https://www.electronjs.org/docs/api/global-shortcut, globalShortcut is used to add event handlers when the application does not have focus:

> The globalShortcut module can register/unregister a global keyboard shortcut with the operating system so that you can customize the operations for various shortcuts.
>
> Note: The shortcut is global; it will work even if the app does not have the keyboard focus. You should not use this module until the ready event of the app module is emitted.

**Comment by tmpolaczyk** [comment]
The following npm packet does exactly what we want: https://www.npmjs.com/package/electron-localshortcut

**Comment by Tommytrg** [comment]
Closed by #1141
