### ISSUE TITLE
ref(encoding): move slip32 code into its own library package

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#127]
PR #120 comes after issue #78 and is the first public implementation of [SLIP-0032][slip32].

It is clearly worth being distributed as a standalone library package on npm.

A separate repository has been created at [node-slip32].

[slip32]: https://github.com/satoshilabs/slips/blob/master/slip-0032.md
[node-slip32]: https://github.com/witnet/node-slip32

**Comment by aesedepece** [comment]
`node-slip32` is now [`ts-slip32`][ts-slip32]! (npm package will simply be named `slip32` though)

[ts-slip32]: https://github.com/witnet/ts-slip32

**Comment by mariocao** [comment]
Pull request has been merged and npm package has been published (as [`slip32`][slip32])

[slip32]: https://www.npmjs.com/package/slip32
