### ISSUE TITLE
Assess which UI toolkit to use (if any)

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#13]
Here's a curated list of UI component collections:
https://github.com/vuejs/awesome-vue#component-collections

**Comment by aesedepece** [comment]
Since we are now using React, here are some great compatible UI toolkits:
https://hackernoon.com/the-coolest-react-ui-frameworks-for-your-new-react-app-ad699fffd651

**Comment by kronolynx** [comment]
Semantic UI for react, seems like a good option
https://react.semantic-ui.com

**Comment by aesedepece** [comment]
Great, I have always liked SemanticUI and even used it in a couple of projects. Let's use it.
Please add it as a dependency and use that commit to close this issue. Thanks!
