### ISSUE TITLE
[Discussion] Improve user experience for locked balance

### ISSUE THREAD

**Issue by Tommytrg** [witnet/sheikah#1301]
After the claimming process, some users will have their tokens locked in sheikah due to they have a vesting period. In order to facilitate users know how many token they have but can't be spent, Sheikah shows a ***locked*** balance type. However, balance types aren't explained and Sheikah could provide an explanation in some way: from a popover on hover the balance type to a wizard.

**Comment by aesedepece** [comment]
Let's discuss this early next weel!

**Comment by Tommytrg** [comment]
The output of this discussion are the issues: #1310 and #1311
