### ISSUE TITLE
Discuss user flow when new wallet version is found

### ISSUE THREAD

**Issue by Tommytrg** [witnet/sheikah#1339]
Currently, Sheikah downloads the latest wallet if a newer version is found. However, there are scenarios where we could ask the user if they want to upgrade:
- If a newer major release is found
- If a newer minor release is found

**Comment by gabaldon** [comment]
- Sheikah should update itself when a new major release is available

- Each Sheikah version should install a wallet major release and update the wallet if a new minor release is available
