### ISSUE TITLE
Data request completed showed as IN PROGRESS

### ISSUE THREAD

**Issue by clbartoli** [witnet/sheikah#1376]
A data request completed  with error result `RadonTypes::RadonError(RetrieveTimeout)` is not added in a block but stays as in progress for sheikah. 
Instead, Sheikah should update the state of the dr and set is as error, or something similar.

The node shows 
![image](https://user-images.githubusercontent.com/52961116/94547797-105b7300-0250-11eb-8445-42c7817eaa59.png)

And sheikah

![image](https://user-images.githubusercontent.com/52961116/94547830-1bae9e80-0250-11eb-874c-0382d513f9fa.png)

Also tested from mariocao:fix/balances

**Comment by clbartoli** [comment]
Actually a dr is set as IN PROGRESS even if the result is correct

**Comment by Tommytrg** [comment]
This issue was already closed in witnet/witnet-rust
