### ISSUE TITLE
Receive tx disappears at some point

### ISSUE THREAD

**Issue by clbartoli** [witnet/sheikah#1383]
If we have a received tx and then deploy a dr the received tx disappears (without having reorganization of the chain). However the wits received stay in the wallet, so it looks like it's only a problem of the transactions board. 

In this example I had received 10 wits

![image](https://user-images.githubusercontent.com/52961116/94570910-a3f06c00-026f-11eb-8106-21e14744b741.png)

But it disappears after deploying a dr

![image](https://user-images.githubusercontent.com/52961116/94569982-9e465680-026e-11eb-882c-66f83f94d650.png)

**Comment by Tommytrg** [comment]
This issue was already solved in witnet/witnet-rust
