### ISSUE TITLE
Wrong fee when confirming send tx 

### ISSUE THREAD

**Issue by clbartoli** [witnet/sheikah#1395]
When confirming a send tx the fee is not correct.
In this case the tx was
![image](https://user-images.githubusercontent.com/52961116/94685545-df4f7100-0329-11eb-9661-aa1dbefe7516.png)

and the confirmation showed

![image](https://user-images.githubusercontent.com/52961116/94685594-efffe700-0329-11eb-8d0a-c9e8f90bc433.png)

**Comment by gabaldon** [comment]
solved in #1530
