### ISSUE TITLE
Negative token allocation

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#1402]
![image](https://user-images.githubusercontent.com/1316439/94717409-94951f80-0350-11eb-98f6-e6fe2ad19367.png)

**Comment by aesedepece** [comment]
Turns out that any allocation subject to cliff or delays are affected by the same issue, in which the last installment has near-zero value:
![image](https://user-images.githubusercontent.com/1316439/94816340-f8285700-03fb-11eb-8964-cb13e2cbd704.png)

This sounds to me like the typical issue in which we are iterating from zero instead of one, or we are stopping at `n` instead of `n-1`.

**Comment by Tommytrg** [comment]
This issue was fixed before the first release of the claiming process
