### ISSUE TITLE
Claim file export is missing copies

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#1408]
![image](https://user-images.githubusercontent.com/1316439/94816566-49d0e180-03fc-11eb-850b-3e87f50a38f0.png)

**Comment by aesedepece** [comment]
BTW let me take the chance to suggest renaming "token claim file" as something like "tokens claim receipt". This is clearer about it being the final product of the process, and may also have a psychological effect on the users, as receipts are always seen as somehow important documents that you are expected to keep at least for a while so as to prove that something actually happened.

**Comment by Tommytrg** [comment]
Closed by #1412
