### ISSUE TITLE
Token claiming receipt files are listing addresses, but missing value and timelock

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#1438]
At some point we stopped calculating including values and timelocks in the addresses list that is written into the token claiming receipt files. This totally breaks the validations needed for producing a genesis block.

**Comment by aesedepece** [comment]
Here's the file where something was recently changed that removed the additional data:
https://github.com/witnet/sheikah/blob/1ecc8fc9ecee8fe998fc6720062dc9dc8d277b8f/src/utils.js

**Comment by tmpolaczyk** [comment]
Already fixed
