### ISSUE TITLE
Transaction fees are not being calculated correctly

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#1468]
## Issue description
- Create a value transfer transaction from Sheikah, setting `1 nanoWit` as the "fee per weight unit".
- Transaction preview will show something like `439 nanoWit`. Broadcast the transaction.
- Once confirmed, it will show fee = `1 nanoWit`.

## Expected behavior
The actual transaction fee should match what's shown in the transaction preview.

**Comment by Tommytrg** [comment]
Currently, when Sheikah creates a VTT with `1 nanoWit`, the wallet creates a transaction with this fee and then Sheikah sends it in `sendTransaction` is `1 nanoWit`. This issue will be solved in witnet/witnet-rust#1635.
