### ISSUE TITLE
Implement new wallet states (waiting for node to sync and sync error)

### ISSUE THREAD

**Issue by gabaldon** [witnet/sheikah#1496]
The new UI for showing the status of the wallet should also include the 'waiting for node to sync' status and the 'sync error.' It should show the re-sync functionality only in the latest case.

As @aesedepece suggested:

**Option 1**
<img width="1510" alt="Light (1)" src="https://user-images.githubusercontent.com/16032491/97444375-62191b00-192c-11eb-95f8-41aec7d0300b.png">

**Comment by Tommytrg** [comment]
close by #1504 and #1506
