### ISSUE TITLE
Allow renaming of the wallet on the login screen

### ISSUE THREAD

**Issue by drcpu-github** [witnet/sheikah#1503]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but I would like to be able to rename my wallet.

**Describe the solution you'd like**
Add a pencil icon or something else and allow for editing the name of the wallet in the dropdown box.

**Additional context**
![sheikah_login_edit](https://user-images.githubusercontent.com/65105305/97472689-63f1d700-194a-11eb-89fb-e904123b4dcd.png)

**Comment by aesedepece** [comment]
Wallet renaming is already supported, albeit through the settings inside each wallet. As far as I understand, the request was for renaming, not necessarily from the login screen, so I'll consider this done!
