### ISSUE TITLE
Address is deleted when changing units in create transaction

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/sheikah#1521]
I was creating a transaction but I realized that I needed to change to units, from nanowits to wits:

![Captura de pantalla de 2020-11-12 16-56-20](https://user-images.githubusercontent.com/44604217/98963581-122f7c00-2508-11eb-91dd-4fd55410d171.png)

But when clicking to "nanowits" in order to change the unit, the address field is deleted:

![Captura de pantalla de 2020-11-12 16-56-35](https://user-images.githubusercontent.com/44604217/98963589-15c30300-2508-11eb-9ce1-9caf88bb190e.png)

# Expected behavior

The address field should not be deleted

# Additional details

Sheikah version: commit 6388640591ad597b02486607f02dec52eca53542

**Comment by gabaldon** [comment]
solved in #1508
