### ISSUE TITLE
Implement wallet settings menus 

### ISSUE THREAD

**Issue by gabaldon** [witnet/sheikah#1525]
Implement settings discussed and design in #1547

**Comment by Tommytrg** [comment]
After discussing this, we found the following topics to add in a Settings view:
- General
    - Language
        - English
        - Chinese
        - Russian
        - Spanish
    - Default currency
    - Appearance (switch between dark and light mode)
- Advanced
    - Trigger Resync
    - Export xprv
    - Set node url
- Alerts
    - Select which alerts should be shown
- About
    - ToS
    - Social (It will replace sidebar one)

**Comment by gabaldon** [comment]
closed by #1578
