### ISSUE TITLE
Include weight unit fee input and output to improve UX

### ISSUE THREAD

**Issue by gabaldon** [witnet/sheikah#1526]
In the send transaction view, improve how the "weight unit" is used to define the transaction fee.
The confirmation view should also show the total transaction fee derived from the weight unit used in the previous view.

**Comment by tmpolaczyk** [comment]
In the case of data requests, the confirmation view should clearly indicate the total cost of deploying the data request (fee + other fees + reward)

**Comment by gabaldon** [comment]
duplicated in #1527
