### ISSUE TITLE
 Assess Vue 3

### ISSUE THREAD

**Issue by gabaldon** [witnet/sheikah#1548]

**Comment by Tommytrg** [comment]
After some assessment on this I think we could wait until vue3-migration-helper is released. 

However we should have in mind that the follow breaking changes will affect Sheikah codebase:

- [Global Vue API is changed to use an application instance](https://v3.vuejs.org/guide/migration/global-api.html). We'll have to update how the vue app is created and how other libraries are added to the vue instance.

- [Global and internal APIs have been restructured to be tree-shakable](https://v3.vuejs.org/guide/migration/global-api-treeshaking.html#_3-x-syntax): We'll have to use nextTick in the new way.

- [v-model usage on components has been reworked](https://v3.vuejs.org/guide/migration/v-model.html): We'll have to update the v-model event names in component wrappers.

- [v-on:event.native modifier has been removed](https://v3.vuejs.org/guide/migration/v-on-native-modifier-removed.html#overview): We'll have to remove this modifier from `PasswordValidation.vue` and `DecryptXprv` components

- [ref inside v-for no longer register an array of refs](https://v3.vuejs.org/guide/migration/array-refs.html): We'll have to use a function to set a `$ref` inside `v-for`.

- [Functional components can only be created using a plain function](https://v3.vuejs.org/guide/migration/functional-components.html): Functional components need to be refactors as functions.


- [Async components now require defineAsyncComponent method to be created](https://v3.vuejs.org/guide/migration/async-components.html). Load async componentes will need to be wrapper into `defineAsyncComponent`

- [Render function API changed](https://v3.vuejs.org/guide/migration/render-function-api.html). We'll have to refactor components using render functions according to the new API

WIP

Component events should now be declared with the emits option

https://docs.gitlab.com/ee/development/fe_guide/vue3_migration.html
https://v3.vuejs.org/guide/migration/introduction.html#global-api
