### ISSUE TITLE
Incorrect payment counter for address

### ISSUE THREAD

**Issue by drcpu-github** [witnet/sheikah#1587]
**Describe the bug**
When sending multiple VTT's to one address in the Sheikah wallet (you can put me on Santa's naughty list for doing that), the payments counter is incorrect. I sent 10 VTT's to an address, but the counter only shows that address received 8 payments. I can see all transactions in the transaction view, so they are correctly indexed / discovered, but not counted in the address pane's payment counter. I think this happens when more than one VTT is included in the same block. In my example the VTT's were spread over 8 different blocks and 2 blocks each contained 2 VTT's. 

**To Reproduce**
Send multiple VTT's to one address. They should be included in the same block. The payment counter in the address pane of the Sheikah wallet only counts one per block.

**Expected behavior**
Preferably the correct amount of payments should be shown. 😄 

**Desktop (please complete the following information):**
 - OS: Windows
 - Version Sheikah v1.7.2

**Comment by gabaldon** [comment]
moved to witnet-rust #1815
