### ISSUE TITLE
Change button text when importing wallet, to mention "seed phrase"

### ISSUE THREAD

**Issue by tomsanch** [witnet/sheikah#1592]
**Describe the bug**
For those not aware that "mnemonics" and "12-word seed-phrase" are synonymous, the "Import a wallet" process is confusing. Specifically, at the moment, lots of the documentation and tutorials point to "Importing your wallet using your seed phrase", but the phrase is not mentioned in Sheikah.

**To Reproduce**
1. Open Sheikah
2. Click "Create, import or recover a wallet"
3. Scroll down to see "Import a wallet using Mnemonics"

**Expected behavior**
If agreed, we could change button text to "Import a wallet using Seed Phrase", or we could have a "?" pop-up to explain what mnemonics is.

**Comment by aesedepece** [comment]
I support this idea, as you all know that I've been pushing for eradicating the "mnemonics" term from the UI
