### ISSUE TITLE
style(slip32): fixture names should be camelCase

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#161]
Some of the fixtures in [test/app/main/encoding/fixtures.ts][fixtures] don't follow camelCase naming (e.g.: `prv_hex`).

[fixtures]: https://github.com/witnet/sheikah/blob/master/test/app/main/encoding/fixtures.ts

**Comment by csmoe** [comment]
assign me.

**Comment by aesedepece** [comment]
(Consider it assigned) Thanks!
