### ISSUE TITLE
Add wallet name to export xprv file

### ISSUE THREAD

**Issue by Tommytrg** [witnet/sheikah#1681]
We could improve the UX of importing a wallet from an XPRV file adding the wallet's name file and adding it when the file is imported.

**Comment by gabaldon** [comment]
This feature was implemented in commit: [ab271bf81b7d70c9b842a3636baf564c654df11f](https://github.com/witnet/sheikah/commit/ab271bf81b7d70c9b842a3636baf564c654df11f)
