### ISSUE TITLE
Make changes to synchronize from wallet birth_date

### ISSUE THREAD

**Issue by Tommytrg** [witnet/sheikah#1683]
To improve the user experience of the users when they create a new wallet, it should start synching from the data it was created. To do so, we have to make the following changes in Sheikah:
- [ ] Store the `birth_date` field from `unlock_wallet` method.
- [ ] Add the `birth_date` to the export xprv field.
- [ ] Add `birth_date` argument to `create_wallet` call

The `birth_date` value could be: `"current" | "genesis" | number`.

**Comment by tmpolaczyk** [comment]
@Tommytrg was this done in #1684?

**Comment by Tommytrg** [comment]
closed in #1684
