### ISSUE TITLE
Fix Data Requests Editor

### ISSUE THREAD

**Issue by gabaldon** [witnet/sheikah#1771]
Wrong behaviour in data request editor:

- [ ] Numeric arguments should allow negative and decimal numbers
- [ ] Automatic default operators should show default argument if any
- [ ] Check `getFloat` and `getInteger` operators wrong behaviour
- [ ] Variables should return the output value not the key
- [ ] Allow adding variables to numeric arguments

**Comment by Tommytrg** [comment]
A user has reported that some data requests from here are not working: https://github.com/witnet/witnet-price-feed-examples
