### ISSUE TITLE
Missing inputs in pending transactions ("sending" state)

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/sheikah#1793]
When a transaction is in the "Sending" state, it shows the correct outputs, but the inputs field is empty:

![Captura de pantalla de 2022-08-04 16-39-54](https://user-images.githubusercontent.com/44604217/182876375-3125e393-69c4-4ecd-bf28-bfda134585b1.png)

After the transaction is included in a block, it displays the correct inputs:

![Captura de pantalla de 2022-08-04 16-43-00](https://user-images.githubusercontent.com/44604217/182876382-9af78298-7b3c-4eed-a080-4cae22188e84.png)

I can reproduce this consistently. Sheikah version 1.11.3, wallet version compiled from commit ea98502069a0ae585979b8217961f2c8cfdb66b7 (witnet-rust/master), node version same as wallet, running a local testnet.

**Comment by gabaldon** [comment]
Sheikah receives from the wallet an empty inputs field:

`{"block":{"block_hash":"0000000000000000000000000000000000000000000000000000000000000000","epoch":"0"},"confirmed":false,"data":{"value_transfer":{"inputs":[],"outputs":[{"address":"twit109qzntwweu89ahr45dt02sy2sl0rdwu2chkfem","output_type":"EXTERNAL","time_lock":0,"value":"1"},{"address":"twit1hp3p34h0qdate0nmsz4k52whevrjpzm9h60cvq","output_type":"INTERNAL","time_lock":0,"value":"2999999999"}]}},"hash":"736fa60d756d126d1c6db1bb54934e2baead7622204673019a4c583340d6e515","miner_fee":"0","timestamp":1662624521}`

Once the transaction changes the status to pending (the epoch is not 0), Sheikah receives the inputs:

`{"block":{"block_hash":"34cd2e0dfb9068c28e30bf454bc8b46d8b43aa41d258456ff0f2faa7a0581e28","epoch":"5206810"},"confirmed":false,"data":{"value_transfer":{"inputs":[{"address":"twit167dcrk6evg0xdcyjvml6u6u5rmz2zrv23wxpe9","value":"3000000000"}],"outputs":[{"address":"twit109qzntwweu89ahr45dt02sy2sl0rdwu2chkfem","output_type":"EXTERNAL","time_lock":0,"value":"1"},{"address":"twit1hp3p34h0qdate0nmsz4k52whevrjpzm9h60cvq","output_type":"INTERNAL","time_lock":0,"value":"2999999999"}]}},"hash":"736fa60d756d126d1c6db1bb54934e2baead7622204673019a4c583340d6e515","miner_fee":"0","timestamp":1662624518}`

**Comment by Tommytrg** [comment]
@tmpolaczyk Could we add the `inputs` field before the transaction is `pending`?

**Comment by tmpolaczyk** [comment]
I don't know, but even if we couldn't it would be possible to send an updated transaction once we do know the inputs, so should be possible.

**Comment by aesedepece** [comment]
> @tmpolaczyk Could we add the `inputs` field before the transaction is `pending`?

Yes, it can be added. Afaik, the issue here is that the fully constructed transaction is not currently being included as part of the response to the `send` and `sendRequest` JSONRPC methods on the node side. This can be changed very easily (specially after some of the changes I made in https://github.com/witnet/witnet-rust/pull/2261).

**Comment by aesedepece** [comment]
@Tommytrg taking into consideration that the relevant changes need to be made in witnet-rust, what do you want to do with this issue for the scope of the current sprint? I'd support removing it from the sprint for now, and rather opening a new one on witnet-rust.

**Comment by Tommytrg** [comment]
This issue was estimated with the idea of checking if it was an error in Shiekah or not. IMO this issue can be closed in Sheikah and we need to open a new one in witnet-rust
