### ISSUE TITLE
Vue state management libraries research

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#18]
We had challenges with `vuex`, so @kronolynx is exploring alternatives.
Progress on his findings shall be tracked here.

**Comment by horrigan** [comment]
Why not to use React/Redux they have amazing tool redux-obervables(RXJS + Redux)? I said this from the very beginning. It's the best tool for state management.

**Comment by aesedepece** [comment]
@horrigan Thanks for the feedback! That's something we've been considering for a while. We will make up our minds in the following hours.

**Comment by aesedepece** [comment]
We finally decided to go with React and Redux. Using a more popular stack guarantees stability and compatibility and eases external contribution.
