### ISSUE TITLE
Radon array sort not working

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/sheikah#1821]
![Captura de pantalla de 2022-10-26 10-39-08](https://user-images.githubusercontent.com/44604217/197978231-e63295e2-532c-44a9-9b4d-0ea772c3bccd.png)

I am unable to sort an array. The tooltip says "Sort the input Array in 16 order", that's wrong, and 16 is the opcode for ArrayCount. And I don't want to use ArrayCount, I just want to sort the array by value.

Also, after the count operator sheikah draw an "integer" box, and hovering over it says "Click 'Try Data Request' to see the partial result". But Try Data Request is already enabled here, so that tooltip is wrong.

**Comment by aesedepece** [comment]
Well the example in the screenshot does not make much sense to me. Remember that `sort` operates as "map and sort". I don't see why you would do a `count` on the array items hehehe.

In any case, this functionality seems to be broken in the exact way that you described. Look at this other example:

![image](https://github.com/witnet/sheikah/assets/1316439/37cd693f-57c1-40b6-a4e1-5d4ea7726b5d)

You can download the example here:
[template.json.zip](https://github.com/witnet/sheikah/files/11816914/template.json.zip)

**Comment by Tommytrg** [comment]
Closed in #1860
