### ISSUE TITLE
Edit source scripts view looks bad with long URLs (horizontal scroll)

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/sheikah#1822]
![Captura de pantalla de 2022-10-26 10-51-47](https://user-images.githubusercontent.com/44604217/197980913-d783cde8-59c4-4029-89bd-6e8555027bcd.png)

**Comment by aesedepece** [comment]
Leaving this here just in case it helps :stuck_out_tongue_closed_eyes: 
```css
overflow-wrap: break-word;
word-wrap: break-word;
```
