### ISSUE TITLE
Add shortcut to delete Sheikah files

### ISSUE THREAD

**Issue by gabaldon** [witnet/sheikah#1868]
- Delete .sheikah:

| OS | Files to delete |
| --- | --- |
| macOS | ~/Desktop/.sheikah |
| Linux | ~/.Sheikah |
| Windows | C:\Users\user\.sheikah |

- Delete your wallet storage

| OS | Files to delete |
| --- | --- |
| macOS | ~/Desktop/.sheikah ~/Library/Application\Support/witnet.witnet/ ~/Library/Application\Support/Sheikah\Witnet\wallet/ |
| Linux | ~/.Sheikah  ~/.local/share/witnet/witnet_wallet.db |
| Windows | C:\Users\user\.sheikah  C:\users\{YOUR_USERNAME}\AppData\Local\witnet |

**Comment by Tommytrg** [comment]
Closed by #1883
