### ISSUE TITLE
Release 1.12.0

### ISSUE THREAD

**Issue by gabaldon** [witnet/sheikah#1893]
1.12.0-rc.1 needs to be e2e tested in windows, mac and linux.

Flows to test:

- Login and syncronize. Check notification of synchronization progress is shown
- Check transactions list is correctly paginated
- Generate address and send transaction
- Go to editor > run data request
- Go to editor > Export DR as Javascript file
- Go to editor > Export DR as Sheikah template
- Go to Settings > General > Change language
- Go to Settings > Advance > Export XPRV
- Go to Settings > Advance > Update wallet name
- Go to Settings > Advance > Re-establish Sheikah backend
- Create wallet and Import XPRV
- Create wallet importing mnemonics

**Comment by Tommytrg** [comment]
[1.12.0-rc.1](https://github.com/witnet/sheikah/releases/tag/untagged-4e74d3d77a7a6f4e7d7b)

**Comment by aesedepece** [comment]
> [1.12.0-rc.1](https://github.com/witnet/sheikah/releases/tag/untagged-4e74d3d77a7a6f4e7d7b)

I'll test it!

**Comment by gabaldon** [comment]
https://github.com/witnet/sheikah/releases/tag/v1.12.1
