### ISSUE TITLE
Define color palette as scss variables

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#208]

**Comment by Tommytrg** [comment]
I propose use the following naming convention for color variables:
 ### $color-(mod-name)-(color name)
For example, current colors generating mod-name with a [color name generator](chir.ag/projects/name-that-color) are:
+ $color-alabaster-white: #f8f8f8;
+ $color-boulder-grey: #7B7B7B;
+ $color-cornflower-blue: #6495ed;
+ $color-electric-violet: #8b00ff;
+ $color-mineshaft-black: #262626;
+ $color-royal-blue:#4169e1;
+ $color-tropical-blue:#c3ddf9;
+ $color-wepeep-red: #f7dbe6;

**Comment by Tommytrg** [comment]
Another naming convention to follow could be ant's convention:
 ### $(color-name)-(level)
Advantages of this convention is we could use [ant's color palettes](https://ant.design/docs/spec/colors) directly.
