### ISSUE TITLE
Handler type declaration is wrong

### ISSUE THREAD

**Issue by anler** [witnet/sheikah#216]
**Describe the bug**

The declaration of the Handler type is wrong: 
```typescript
export type Handler<T> =
  (system: T, params: Array<JsonSerializable>) => Promise<JsonSerializable | void>
```

since there is no guarantee that the `params` attribute of the request is an array, it could be any `JsonSerializable` value.

**To Reproduce**

If a client sends a request with params set to anything else but an array, any handler relying upon params being an array would fail with an exception.

**Expected behavior**

We should use the more broad type `JsonSerializable` instead.

**Comment by aesedepece** [comment]
You are completely right. Great point.

**Comment by anler** [comment]
🐒 I forgot I changed the protocol a bit to enforce params to [always be an array](https://github.com/witnet/sheikah/blob/master/app/common/ipc-protocol.ts#L42) ... closing the issue.
