### ISSUE TITLE
feat: discover related addresses, TXs and UTXOs upon wallet import

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#226]
From #218 :

    2.2.3. [m] Ask rust-witnet for related TXs and UTXOs, add to wallet, persist wallet, return udpater

This is locked (as `rust-witnet` is not mature enough yet), but let's have this issue here and make our best to unlock it as soon as we can.

**Comment by Tommytrg** [comment]
This issue is deprecated with the new structure of Sheikah that starts with #608.
