### ISSUE TITLE
Assess backend <> frontend communication solutions for Electron

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#23]

**Comment by kronolynx** [comment]
Electron has IPC
https://electronjs.org/docs/api/ipc-main

```javascript
// In main process.
  const {ipcMain} = require('electron')
  ipcMain.on('asynchronous-message', (event, arg) => {
    console.log(arg) // prints "ping"
    event.sender.send('asynchronous-reply', 'pong')
  })
  
  ipcMain.on('synchronous-message', (event, arg) => {
    console.log(arg) // prints "ping"
    event.returnValue = 'pong'
  })

// In renderer process (web page).
  const {ipcRenderer} = require('electron')
  console.log(ipcRenderer.sendSync('synchronous-message', 'ping')) // prints "pong"
  
  ipcRenderer.on('asynchronous-reply', (event, arg) => {
    console.log(arg) // prints "pong"
  })
  ipcRenderer.send('asynchronous-message', 'ping')
```

**Comment by aesedepece** [comment]
Apparently, native Electron IPC will do the trick.

Are you aware of any security considerations? I mean, do you know if it's safe to send sensitive data over IPC? I'm concerned about sufficiently permissioned third-party processes sniffing data in the IPC channel.

**Comment by aesedepece** [comment]
Well, I guess you can do nothing against something like this:
```
strace -ewrite -p $PID
```
So, ok, any process run by a root-enabled user can tamper with IPC. But that's a safe assumption, as they can likely tamper with share memory too.

Wrapping up, let's go with IPC!

**Comment by aesedepece** [comment]
OK to close.
