### ISSUE TITLE
fix(security warns): fix security issues that appear in console

### ISSUE THREAD

**Issue by mmartinbar** [witnet/sheikah#237]
**Abstract**

Some security warnings appear when launching Electron app in dev (hot) mode:

`Electron Security Warning (Insecure Resources) This renderer process loads resources using insecure protocols. This exposes users of this app to unnecessary security risks. Consider loading the following resources over HTTPS or FTPS.
For more information and help, consult https://electronjs.org/docs/tutorial/security.
This warning will not show up once the app is packaged.`

`Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security Policy set or a policy with "unsafe-eval" enabled. This exposes users of this app to unnecessary security risks.
For more information and help, consult https://electronjs.org/docs/tutorial/security.
This warning will not show up once the app is packaged.`

**Steps to reproduce the problem**

Launch the application with `yarn start`. See the console output at the DevTools.

**Comment by mannycolon** [comment]
Add this meta tag to your `index.html` file 
```html
<meta http-equiv="Content-Security-Policy" content="script-src 'self'">
```
See: [How does content security policy work](https://stackoverflow.com/questions/30280370/how-does-content-security-policy-work)

**Comment by Tommytrg** [comment]
This issue is deprecated with the new structure of Sheikah that starts with #608.
