### ISSUE TITLE
Refactor IPC params

### ISSUE THREAD

**Issue by anler** [witnet/sheikah#245]
## Current

IPC-params is designed this way:

[`params`](https://github.com/witnet/sheikah/blob/master/app/common/ipc-protocol.ts#L42) is restricted to be an `Array<JsonSerializable>`, because the [client](https://github.com/witnet/sheikah/blob/master/app/renderer/api.ts#L91) is designed to receive a variable number of arguments (`...args`). It was designed this way to make it look more like a normal function call.

### pros

- client: passing zero or  more parameters is very natural: `client.request("method", 1, 2, 3)` or `client.request("method")`

### cons

- the RPC-JSON standard is restricted to have params as `Array<JsonSerializable>` instead of `JsonSerializable`
- every time we create a new runtime type for parsing a handler's params, we have to wrap all params in a [`io-ts/tuple`](https://github.com/gcanti/io-ts#implemented-types--combinators) type since params are always an array

## New way RFC

To avoid using [`io-ts/tuple`](https://github.com/gcanti/io-ts#implemented-types--combinators) to wrap every runtime type we need in the handlers, we could change the design of the client to explicitly receive the params argument (`request(method: string, params: JsonSerializable)`)

### pros

- RPC-JSON compliant
- client: we are able to pass any JSON-serializable type as the value for `params`
- It simplifies the runtime types declaration for handler's params, now instead of wrapping them always in [`io-ts/tuple`](https://github.com/gcanti/io-ts#implemented-types--combinators)  they can be any JSON-serializable type (`string`, `null`, `number`, etc)

### cons

- client: passing zero or  more parameters is not that natural: `client.request("method", [1, 2, 3])`  or `client.request("method", {})` or `client.request("method")` (later will by default be `null`)

**Comment by aesedepece** [comment]
Sounds good!

**Comment by aesedepece** [comment]
Closed by #258
