### ISSUE TITLE
Mnemonic's isValid behaves like if it was isNotValid

### ISSUE THREAD

**Issue by anler** [witnet/sheikah#266]
**Describe the bug**
The `isValid` function in `app/main/crypto/mnemonic.ts` is the opposite of what it should be: returns `true` for invalid mnemonics, and `false` for valid ones.

**To Reproduce**
```ts
import {generate, isValid} from "app/main/crypto/mnemonic"

assert(isValid(generate()) // this fails
assert(isValid("foo"))        // this does not fail
```

**Expected behavior**
It should return `true` for generated mnemonics

**Comment by aesedepece** [comment]
Wow that was silly :rofl:
