### ISSUE TITLE
fix(build): yarn test leaves transpilation by-products under config directory

### ISSUE THREAD

**Issue by mmartinbar** [witnet/sheikah#275]
**Describe the bug**
Running the tests leaves transpilation products in a `dist` directory under the `config` directory.

**To Reproduce**
1. Run `yarn clean` to delete `dist` directory. 
2. Delete `config/dist` (if it exists) directory.
3. Execute `yarn test`.
4. Check that `config/dist` directory appears with the transpilation products.

**Expected behavior**
Transpilation products should be placed under the `dist` directory, not inside `config/dist`.

**Comment by anler** [comment]
I noticed it but had no idea what caused it
![](https://media.giphy.com/media/zqF12WgFHJevu/giphy.gif)
