### ISSUE TITLE
style(login-form): collapse sidebar past wallet selection screen

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#302]
Once a wallet has been selected for unlocking, the sidebar is redundant, distracting and gives navigation options (app settings) that break the linearity of the form.

#### Actions
Once the wallet selection screen is past, the sidebar should be collapsed by restyling it:
- Same background
- No contents
- Only a few pixels width

**Comment by aesedepece** [comment]
Preview:

![Collapsed sidebar preview](https://image.ibb.co/nPzZ0e/collapsed_sidebar.png)

**Comment by Tommytrg** [comment]
According to the [specification](https://www.w3.org/TR/css3-grid-layout/#track-sizing), transitions should work on css grid properties but they are not yet implemented on browsers. More information can be found [here](https://stackoverflow.com/questions/43911880/using-css-transitions-in-css-grid-layout).

 Our approach to add transitions on css grid items could be add a wrapper over them which their transition.
