### ISSUE TITLE
Notification toasts

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#307]
#### User story

_As a user of the Sheikah prototype, I want_:
- _the app to give me friendly feedback every time I click on functionalities that are not yet implemented._
- _that kind of notifications to be as little annoying as possible and not to require my action to dismiss them (e.g: modals are not welcome)._

#### Actionables
- Implement an app wide, non obstructive notifications system.
- Base the UI for such system on [antd's own toasts][antd].
- Note that this solution may need the toast component to be always present in the DOM.
- Instantiate such service in the app index or root and pass it down to containers via `services` React prop (just like we do with `apiClient`).
- Stylize the toast (@aesedepece will provide design).

[antd]: https://mobile.ant.design/components/toast

**Comment by aesedepece** [comment]
The toast message should resemble:
```stylus
background: rgba(0, 0, 0, .8)
border-radius: 50%
color: white
font-size: 14px
margin: 22px 50px 20px 50px
```

**Comment by aesedepece** [comment]
![Toast preview](https://image.ibb.co/dfZmwK/toast.png)

**Comment by mariocao** [comment]
The desktop version of the antd Toast is the [Message](https://ant.design/components/message/) component.
