### ISSUE TITLE
Some wallet-related IPC runtime types are misplaced

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#326]
#### Issue description
As @mmartinbar pointed out in [issue #317's discussion][317], there may be some wallet-related IPC runtime types that are incorrectly placed inside the `runtimeTypes/storage` folder instead of `runtimeTypes/ipc` one.

#### Actionables
We just need to make sure everything is in the right place.

[317]: https://github.com/witnet/sheikah/pull/317#discussion_r208864174

**Comment by mmartinbar** [comment]
Already implemented in [this branch](https://github.com/mmartinbar/sheikah/tree/feat-326). Need to review it and merge it. Not done as this may not be the priority of the sprint.

**Comment by Tommytrg** [comment]
This issue is deprecated with the new structure of Sheikah that starts with #608.
