### ISSUE TITLE
Error-building functions declared by main process are being used by renderer process

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#327]
#### Issue description
As pointed out by @mmartinbar in [issue #317's discussion][317], there are some error building functions declared and exported by main process code that are later used by renderer process code.

Even though this doesn't have any security implications or whatnot, it's just a little ugly and a kind of counter pattern to consume main code from the renderer. That's precisely the role of the `common` folder: holding shared "library code".

#### Actionables
- Moving error building functions into the `common` folder.
- (Optionally) generalizing all the error building functions into a single function.

[317]: https://github.com/witnet/sheikah/pull/317#discussion_r208869633

**Comment by Tommytrg** [comment]
This issue is deprecated with the new structure of Sheikah that starts with #608.
