### ISSUE TITLE
Create closeWallet API handler

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#339]
#### Motivation
As stated in issue #338:

_As a Sheikah wallet user, I want to be able to close my current open wallet so that I can go back to the login screen and open a different wallet or create a new one._

This issue covers creating the `closeWallet` API wallet. Creation of the client side method will be issue #340 and integration in the UI is issue #338 itself.

#### Tasks
_Someone tackling this issue shall:_
- Understand how API handlers work.
- Create a new `closeWallet` API handler at `app/main/api/handlers`.
- Add the handler to [routes.ts].
- Test-cover this.

#### Deliverables
_A potential PR closing this issue shall provide:_
- a new API handler for method `closeWallet` that closes the `walletStorage`, sets the `appStateManager.state.wallet` value to undefined and returns void.
- a route for the new handler in [routes.ts]
- tests

[routes.ts]: https://github.com/witnet/sheikah/blob/master/app/main/api/routes.ts

**Comment by Tommytrg** [comment]
This issue is deprecated with the new structure of Sheikah that starts with #608.
