### ISSUE TITLE
Implement listcards with empty states

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#343]
#### User story
_As a Sheikah prototype user, when I create a new wallet I expect the UI to show nice empty states acknowledging that there's not much to list there._

#### Considerations
- "listcards" are card components whose content is a list containing one or more uniform members (items of the same type).  The transactions list is an example of listcard.
- listcards are not yet implemented as reusable components. That's one of the tasks in this issue.
- When one of these lists have no members, it makes no sense to render the card component, as it would be collapsed because of the lack of actual contents and would look like a 0px tall box with a 1px border, which is equivalent to a 2px thick horizontal line. 
- Thus the need of using empty states. If the list of components passed to the list component as children has zero members, the listcard component should not render a card at all but the empty state, which is not contained in a card at all (see design in #341).
- Empty states may carry different labels for different listcards.

#### Tasks
_Someone tackling this issue shall:_
1. Read issue #341.
2. Get familiar with [lists] and [cards].
3. Implement a new `ListCard` component supporting empty states.
4. Modify "[the wrapper]" (see issue #119 or ask @Tommytrg for more info) so that it doesn't force the content to look like a card. This is, the content can be anything.
5. Task 4 will break the styling of current usages of the wrapper. Find those usages and replace them for `DefaultCard` or `ListCard` depending on the case.

#### Deliverables
_A potential PR closing this issue shall provide:_
- A `ListCard` component that conditionally renders the value of `this.props.items` or the empty state depending on whether `this.props.items.length` is greater than `0`. If the optional prop `label` is provided, the empty state should read `No ${this.props.label} to show`, otherwise `Nothing to show`.

[lists]: https://github.com/witnet/sheikah/blob/master/app/renderer/ui/components/list/index.tsx
[cards]: https://github.com/witnet/sheikah/blob/master/app/renderer/ui/components/card/default/index.tsx
[the wrapper]: https://github.com/witnet/sheikah/blob/master/app/renderer/ui/components/wrapper/index.tsx

**Comment by aesedepece** [comment]
Because of tasks 4 and 5, this issue was likely underestimated.

**Comment by Tommytrg** [comment]
Closed by #429.
