### ISSUE TITLE
Colored dot indicators UI polish

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#344]
#### Motivation
We use a number of colored dots across the UI as visual indicators of the state of many elements of the application. These dots can take different colors with very obvious semantics to the user: green is positive, yellow is neutral and red is negative.

The coloring and sizing of the dots does not currently match what the screenshots in issue #16 are depicting.

#### Tasks
_Someone tackling this issue shall:_
1. Get the actual sizes of the dots from the SVG sketch (this is available in our KeyBase team folder)
2. Ensure that "positive", "neutral" and "negative" colors are defined in our theme.
3. Make a reusable component for dots (`DotIndicator`) that can take "positive", "neutral" or "negative" as a `mood` prop and applies the matching colors as defined in our theme.
4. Discover current usages of colored dots indicators.
5. Replace current usages with instances of the reusable component.

#### Deliverables:
_A potential PR closing this issue shall provide:_
- a reusable component for dots (`DotIndicator`) that can take "positive", "neutral" or "negative" as a `mood` prop and applies the matching colors as defined in our theme.
- all usages of colored dots indicators replaced by instances of the `DotIndicator` component.

**Comment by aesedepece** [comment]
This issue was likely underestimated :see_no_evil:

**Comment by mariocao** [comment]
Closed in 7abc6a8
