### ISSUE TITLE
fix(handler): encryptWallet handler should update plain storage with WalletInfo

### ISSUE THREAD

**Issue by mmartinbar** [witnet/sheikah#349]
**Describe the bug**

The encryptWallet handler in the main process is the one in charge of creating the wallet from a password, a caption and a seed. The steps that are currently done in order to do this are:

1. Receive password (and caption optionally) from front-end
2. Get seed from unconsolidated data (and generate caption if it was not received in step 1)
3. Initialize a wallet data structure with the given caption (and an id generated at this point from the seed)
4. Initialize wallet AES storage with the password and the generated id
5. Store serialized (encoded) wallet in AES storage
6. Replace wallet storage in the system with current wallet storage
7. Remove unconsolidated wallet from the system

However, these steps are missing the logic that is related to update plain storage with the WalletInfo of the newly created wallet. This is an idea of what should be done:

1-5. Same logic as before.
6. Update plain storage to store the WalletInfo (id and caption) of the newly created wallet.
7. Update array of WalletInfos in the system to contain the new WalletInfo.
8. Replace wallet storage in the system with current wallet storage.
9. Remove unconsolidated wallet from the system.

**To Reproduce**

1. Start Sheikah with `yarn start`
2. Create a new wallet from mnemonics
3. Check that Sheikah successfully redirects to the main wallet page (and a new folder appears at `~/.sheikah/storage`, being the id of the wallet the name of the folder)
3. Close Sheikah
4. Restart Sheikah with `yarn start`
5. Check that Sheikah does not detect any existing wallet

**Expected behavior**

1. Start Sheikah with `yarn start`
2. Create a new wallet from mnemonics
3. Check that Sheikah successfully redirects to the main wallet page (and a new folder appears at `~/.sheikah/storage`, being the id of the wallet the name of the folder)
3. Close Sheikah
4. Restart Sheikah with `yarn start`
5. Check that Sheikah offers the posibility of unlocking the previously created wallet

**Comment by aesedepece** [comment]
Great point. This got totally overlooked. It's now a priority to add the
plain storage updater to the promise chain.

Reverting wallet storage upon failure would be nice for the sake of
clearing up unused disk space, yet it's not strictly needed as stored
wallets will be simply ignored if not indexed and persisted in walletInfos.

**Comment by mmartinbar** [comment]
If it's okay with you, I'll move the error handling to another issue in order to safely close this one.  I think we (or perhaps just I :sweat_smile:) need to think more carefully about what you said @aesedepece, because I have the intuition that strange things can happen if we don't handle the errors. It's not only the disk space I'm worried about but also leaving an inconsistent app state in the main process. The app state is also updated with the wallet storage and the wallet infos and I wonder if situations of the kind "updating the wallet storage in the app state even if the wallet could not be created" can happen (though perhaps under extremely rare conditions).
