### ISSUE TITLE
fix(handlers): error handling in handlers' promise chain in main process

### ISSUE THREAD

**Issue by mmartinbar** [witnet/sheikah#358]
In the case of an error in the handlers' promise chain, we should undo all actions that need to be undone and that were performed in the promise chain until the error occurred. These are some examples of things that may have to be reverted:
- Updates to level storage
- Updates to the backend's app state

IMHO, it is important that we do so in order to keep our databases and the app state clean and consistent.

Discussed in [issue #325](https://github.com/witnet/sheikah/pull/325) and in the comments of issue #349.

Also, there have been some comments about the right approach for handling these errors (see [discussion](https://github.com/witnet/sheikah/pull/356))

**Comment by Tommytrg** [comment]
This issue is deprecated with the new structure of Sheikah that starts with #608.
