### ISSUE TITLE
feat(ui): improve navigation in new wallet form

### ISSUE THREAD

**Issue by mmartinbar** [witnet/sheikah#365]
Once in the new wallet form, it is not possible to do anything but finishing the creation of a wallet (or closing the application).

If the user has no wallets, this is the right thing to do. If the user has other wallets, perhaps the right thing to do would be to allow him to go back to the option of selecting a wallet.

**Comment by mariocao** [comment]
This issue has been closed by @aesedepece in 9e00e6f87f798b9a96731949cbf9845503783c58 :1st_place_medal:
