### ISSUE TITLE
fix(wallet-form): mismatching mnemonics error in new wallet flow

### ISSUE THREAD

**Issue by mmartinbar** [witnet/sheikah#370]
**Describe the bug**
In the new wallet form, when going back from the "Wallet encryption password" step to the "Wallet seed confirmation" step, we reach a point of no return. Clicking "Next" in the "Wallet seed confirmation" step gives nothing but "Invalid mnemonics" errors.

**To Reproduce**
1. Use the new wallet form in Sheikah up to the "Wallet encryption password" step
2. In that step, click the "Back" button
3. When back to the "Wallet seed confirmation", click to the "Next" button without modifying anything (valid mnemonics are in the input field).
4. See that the "Invalid mnemonics" error appears even though mnemonics are valid  

**Expected behavior**
The "Wallet encryption password" should be prompted again if mnemonics introduced by user are valid.

**Clues**
Quick early debugging of the issue tells us that the "Invalid mnemonics" error is caused by the backend. The backend detects "Mismatching mnemonics" at the "importSeed" handler and that is because the unconsolidated wallet in the app state does not longer contain any mnemonics. They are removed from the app state once the seed is generated, which is probably done when the UI moves to the "Wallet encryption password" step.

**Solution**
Perhaps not deleting mnemonics from unconsolidated wallet? Perhaps the UI requesting an app state update with the mnemonics? To be discussed.

**Comment by aesedepece** [comment]
Interesting. It seems to me like we would be better keeping the mnemonics in place until the last step (`encryptWallet`) just in order to allow this behavior, which is perfectly reasonable from the UX side.
