### ISSUE TITLE
Improve copy for "Passwords must match"

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#371]
The _"Passwords must match"_ copy shown as an error in the wallet creation form if the encryption password and the value of its confirmation field mismatch sounds a little poor to me. I think we should find a more idiomatic copy.

From a quick Google search, I found:
- _"Your password and confirmation password do not match"_ (Adobe)
- _"Password does not match the confirm password"_ (Microsoft)
- _"Password and confirm password does not match"_ (Microsoft)
- _"'Confirm Password' and 'Password' do not match"_ (Microsoft)
- _"Passwords do not match, please retype"_ (Mozilla)

#### Actionables
_Someone tackling this issue shall:_ 
1. Review proposed copies and extend the list if considered necessary.
2. Collect feedback from the rest of team on what's the best copy. This can be posted as an open question in our team Telegram chatroom.
3. Replace the copy.

**Comment by mmartinbar** [comment]
'Password' and 'confirm password' do not match. Like it?
