### ISSUE TITLE
Modify getWallet, app state, tests, etc. to hold transaction data collection

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#402]
#### Motivation
By virtue of #401, we are moving transaction data into a different collection that is to be stored under a separate `transactions` key inside the wallet storage.

This has strong implications to many different parts of Sheikah, as the renderable app state doesn't depend solely on the currently open wallet any more. We now have a separate data structure that can be combined with the wallet itself to produce in real time everything we need to render (e.g.: the transactions list).

Namely, at least we need to modify:
- [ ] `getWallet`, to make it read `transactions` from wallet storage, put it into main process app state and return it inside its return type (`AppState` and `GetWalletSuccess` need to be extended).
- [ ] tests.

**Comment by aesedepece** [comment]
This is blocked for the time being (out of the prototype's scope) :wink:

**Comment by Tommytrg** [comment]
This issue is deprecated with the new structure of Sheikah that starts with #608.
