### ISSUE TITLE
Path used for LevelDB might not work in all supported platforms

### ISSUE THREAD

**Issue by anler** [witnet/sheikah#407]
**Describe the bug**
When creating the LevelDB database [we are using a path](https://github.com/witnet/sheikah/blob/master/app/main/storage/jsonAesLevel.ts#L35) that might not work in all supported platform (for instance Windows). A better solution would be to use a different path depending on the platform. [Electron Log](https://github.com/megahertz/electron-log/blob/master/lib/transports/file/find-log-path.js#L24) is nice example of how to do this.

**Comment by aesedepece** [comment]
In theory, [`path.normalize()`](https://millermedeiros.github.io/mdoc/examples/node_api/doc/path.html#path.normalize) already handles that for us.

**Comment by anler** [comment]
I don't mean the path separator, I mean for example that Windows may not allow a folder named `.sheikah` (with a dot `.`)

**Comment by aesedepece** [comment]
We beg for attention from anyone having Windows to test the app and give feedback on this issue :pray:

**Comment by mmartinbar** [comment]
The path for the levelDB storage in Windows for the user `Alice` is `DriveUnit:\Users\Alice\.sheikah\storage` as expected. It seems that there are no problems related to that.
