### ISSUE TITLE
Run tests in parallel when not in CI environment

### ISSUE THREAD

**Issue by anler** [witnet/sheikah#422]
We added the `--runInBand` option to `yarn test` to run the tests in band in Travis, the problem is that this also forces us to run the tests in band in our local machines (with a lot of resources that can be used to run them in parallel). We could rewrite the `yarn test` task as follows that will run the tests in band in Travis but in parallel in our local machines:

```diff
-    "test": "jest -c config/jest.js --runInBand test/app",
+    "test": "if [ $CI ]; then echo --runInBand; fi | xargs jest -c config/jest.js test/app",
```

**Comment by aesedepece** [comment]
Oh great point. This caused my laptop to annoyingly freeze some minutes ago.

**Comment by Tommytrg** [comment]
This issue is deprecated with the new structure of Sheikah that starts with #608.
