### ISSUE TITLE
INVALID_WALLET_TYPE is being wrongly reported as INVALID_PASSWORD

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#433]
**Describe the bug**
`INVALID_WALLET_TYPE` is being wrongly reported as `INVALID_PASSWORD`.

Bottom line: we are having `INVALID_WALLET_TYPE` errors because some change to the wallet schema recently slipped in.

The issue comes from [line 120 in getWallets.ts](https://github.com/witnet/sheikah/blob/master/app/main/api/handlers/getWallet.ts#L120) catching and re-throwing the error throwed by [line 118](https://github.com/witnet/sheikah/blob/master/app/main/api/handlers/getWallet.ts#L118).

**To Reproduce**
1. Try to unlock a wallet that existed before yesterday.
2. Behold the wrong error.

**Expected behavior**
The error message should match the actual error.

**Desktop (please complete the following information):**
 - OS: GNU/Linux 4.17.5-1-MANJARO #1 SMP PREEMPT
 - Node: v8.9.3
 - Electron: v2.0.8

**Comment by mmartinbar** [comment]
So cool, I thought I had forgotten the password :rofl:
