### ISSUE TITLE
Define schema / runtime type of data requests

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#443]
#### Motivation
We need to accommodate the data that will be rendered in the _data requests_ section into a data structure that will be available for the _main_ and _renderer_ processes.

The scope of this issue is modeling the schema for such data structure and implementing the matching runtime type. Implementing the sample data for prefilled wallets is out of its scope (see issue #444  instead).

#### Tasks
_Someone tackling this issue shall:_
- Analyze all the screenshots from Epic #442 to extrapolate what are the properties of data requests.
- Formulate a simple data structure for holding those properties.
- Implement the data structure as a runtime type.
- Figure out and propose where in the app state should the list of data requests be linked.
- Modify the _renderer_ side app state to accommodate a list of data requests.

#### Deliverables
_A potential PR closing this issue shall provide:_
- A runtime type for a data request.
- The _renderer_ side app state, updated to accomodate a list of data requests.

**Comment by Tommytrg** [comment]
This issue is deprecated with the new structure of Sheikah that starts with #608.
