### ISSUE TITLE
Implement sample data request data for prefilled wallets

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#444]
##### Motivation

Issue #443 models the schema and implements the runtime type for the data that will be rendered in the _data requests_ section into a data structure that will be available for the _main_ and _renderer_ processes. This issue is a kind of follow-up, as its scope is implementing the sample data for prefilled wallets following that schema.

#### Tasks
_Someone tackling this issue shall:_
- Analyze all the screenshots from Epic #442 and the schema / runtime type resulting from issue #443 to understand what are the properties of data requests and identify what the prefilled values should be.
- Implement the object holding the prefilled data.

#### Deliverables
_A potential PR closing this issue shall provide:_
- An object abiding by the schema resulting from issue #443 and holding the prefilled wallet.

**Comment by Tommytrg** [comment]
This issue is deprecated with the new structure of Sheikah that starts with #608.
