### ISSUE TITLE
Implement `/main/smart-contracts/editor` tab

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#454]
#### User story
_As a Witnet user, I expect the Sheikah interface to allow me editing smart contract templates._

#### Motivation
As depicted in Issue #17, the "Smart contracts" section has a tab called "Editor". This tab allows users to create and edit smart contract templates.

Note that you create and edit templates, which are parametric (or not). Then, every time you deploy those templates you create new instances with different parameters. This is not done through the editor but through the deployment/instantiation wizard, which falls out of the scope of the technology preview.

#### Considerations
- For demo purposes, this section will be completely mocked in the Sheikah Technology Preview. We are putting SVGs in place and deferring implementation of the actual components as an _only-if-we-have-spare-time-at-the-end-of-the-sprint_ thing. SVGs will be available in our kb team folder.

#### Tasks
- Analyze all the screenshots from Issue #17 .
- Create the route for this tab.
- Implement the tab.

**Comment by mariocao** [comment]
The `Editor` placeholder is prepared to be used in the PR corresponding to the issue #453.
