### ISSUE TITLE
Refactor all Buffer used in common code

### ISSUE THREAD

**Issue by mmartinbar** [witnet/sheikah#460]
Code under `app/common` directory is meant to be used from both back-end and front-end (main and renderer processes). However, `Buffer` is a module from `Node.js` and so its usage would not be correct from the renderer side.

See what should be used instead (something like a byte array perhaps) and refactor the code to use it.

**Comment by Tommytrg** [comment]
This issue is deprecated with the new structure of Sheikah that starts with #608.
