### ISSUE TITLE
Sizing of main screen not correct at launch

### ISSUE THREAD

**Issue by jrmoreau** [witnet/sheikah#472]
**Describe the bug**
When Sheikah finishes building the screen does not fit properly into the view on the transaction section

**Expected behavior**
The view should show the entire screen upon launch 

**Screenshots**
 (on launch)
<img width="1039" alt="screen shot 2018-09-03 at 12 00 39 pm" src="https://user-images.githubusercontent.com/1614127/44995433-02ec3580-af71-11e8-890b-a27f93a3b5b7.png">

(after maximizing the screen)
<img width="1680" alt="screen shot 2018-09-03 at 12 02 10 pm" src="https://user-images.githubusercontent.com/1614127/44995494-3a5ae200-af71-11e8-9877-97a453173994.png">

**Desktop (please complete the following information):**
 - OS: iOS

**Additional context**
the screen is basically too wide for the default size of the electron app when it launches. you'd need to maximize the view of Sheikah to get everything to fit.

**Comment by aesedepece** [comment]
Fixed by @Tommytrg in 653ef471b83b2932b91b8140f7096bb9a6ec1786.
