### ISSUE TITLE
Font awesome icons not showing in Windows

### ISSUE THREAD

**Issue by mmartinbar** [witnet/sheikah#493]
This is a screenshot:

![sheikah_windows_fa_icons](https://user-images.githubusercontent.com/23116308/45039985-2d1f1f80-b065-11e8-85bd-9fb348a42743.PNG)

**Comment by aesedepece** [comment]
THE DRAMA

**Comment by mmartinbar** [comment]
[This](https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting) says that "Windows 10 can be configured via its registry to block untrusted fonts.". Don't know if this could be why.

**Comment by Tommytrg** [comment]
This issue is deprecated with the new structure of Sheikah that starts with #608.
