### ISSUE TITLE
Polish links in Sheikah application top menu

### ISSUE THREAD

**Issue by mmartinbar** [witnet/sheikah#494]
**Describe the bug**

The application top menu (File/View/Help) has some links that could be polished.
- File/Open -> perhaps this could be removed as it does nothing.
- Help/* -> all these links (now pointing to electron stuff) could point to Witnet community links (github, webpage...)

**Desktop:**
 - OS: Windows & Linux

**Comment by aesedepece** [comment]
Great idea for repurposing the "Help" menu.

**Comment by aesedepece** [comment]
Closed by #507 in dca946c606bf59a3cf4a65778420bf9c5940361b.
