### ISSUE TITLE
Side bar instruction text too light to read

### ISSUE THREAD

**Issue by jrmoreau** [witnet/sheikah#499]
**Describe the bug**
The instructional text on the side bar is too light to read easily. My eyes strain to read it. 

**Expected behavior**
Something darker would be easier to read. Better yet, a text overlay popup might even be better if it's centered over the main Skeikah screen

**Comment by aesedepece** [comment]
Correct me if I'm wrong, but I think this is a duplicate of #478. Let's continue discussion there :wink:
