### ISSUE TITLE
Data Request Text Edit Suggestions

### ISSUE THREAD

**Issue by jrmoreau** [witnet/sheikah#501]
Data requests are ~~simple~~ scripts that tell Witnet where to retrieve data. ~~from websites, APIs            or other blockchains and deliver it wherever it is needed.~~ You can think of them as the            "if-this-then-that" of blockchains.
         
Data requests ~~can~~ perform transformations and aggregations on data coming from several            sources. When delivering the result**s,** they can also use several targets: from pushing the            data to a web server using a secure WebHook, to reporting it directly to a~~n Ethereum or            RChain~~ smart contract.
 
Every time you deploy a data request, you can choose how many Witnet nodes will be            processing the request. **This** is called the "replication factor." The more nodes, **[I think 'safe' isn't the word we want to use? Is 'fidelity' better?]** ~~the safer~~ **For each additional replication factor, there will be additional costs to the requester.**
   
Sheikah does not manage data requests directly but uses ~~more~~ flexible data request            templates instead. These templates can later be deployed to Witnet using ~~specific~~        **customizable** parameters.

**Comment by mariocao** [comment]
Regarding the "safe" or "fidelity" sentence, possible sentence:
`The more nodes, the higher the fidelity of the request will be.`

**Comment by aesedepece** [comment]
Solved by @mariocao in d0a49611a497435a9aee6c0e97c37e6b9f9b1f5c.

**Comment by jrmoreau** [comment]
@mariocao @aesedepece "The net fidelity of the data can be increased by ensuring more nodes are available in the request." Does this make sense?
