### ISSUE TITLE
Wrappers/cards expand too much when few payment requests

### ISSUE THREAD

**Issue by mmartinbar** [witnet/sheikah#532]
**Describe the bug**
Wrappers/cards expand too much when there are few payment requests.

**To Reproduce**
1. Create a new wallet (not prefilled)
2. Go to the "Receive" tab

**Screenshots**
![image](https://user-images.githubusercontent.com/23116308/45207384-1f95af80-b288-11e8-8cba-a8328109131c.png)

**Desktop (please complete the following information):**
 - Manjaro Hakoila

**Comment by aesedepece** [comment]
Solved by @anler in #528.
