### ISSUE TITLE
Fix Storybook 

### ISSUE THREAD

**Issue by kengork** [witnet/sheikah#543]
Storybook not working when executing `yarn storybook`
Solution:
Update Storybook version
**Screenshots**
<img width="1436" alt="screenshot 2019-01-09 at 17 20 38" src="https://user-images.githubusercontent.com/10687542/50912686-0322a300-1433-11e9-9dde-bdba3fc0a25e.png">

**Comment by Tommytrg** [comment]
The first approach to close this issue could be update to storybook 4 and check that at least the following tools are implemented: typescript, jest, antd.
