### ISSUE TITLE
Component unit testing

### ISSUE THREAD

**Issue by Tommytrg** [witnet/sheikah#571]
List of components that need a unit test.
### Alert
- [ ] Alert default
- [ ] Alert message
### Balance
- [ ] Balance
### Bars
- [ ] Sidebar
- [ ] Topbar
### Button
- [ ] Button action
- [ ] Button default
- [ ] Button link
- [ ] Button navigation
- [ ] Button option
### Card
- [ ] Card default
- [ ] Card marketplace product
- [ ] Card navigation
### Dot indicator
- [ ] Dot indicator
### Dropdown
- [ ] Dropdown bordered
- [ ] Dropdown default
### Empty state
- [ ] Empty state
### Generic message
- [ ] Generic message
### Input
- [ ] Input amount 
- [ ] Input big
- [ ] Input amount
- [ ] Input checkbox
- [ ] Input default
- [ ] Input switch
- [ ] Input underlined
### List
- [ ] List
### Loading modal
- [ ] Loading modal
### Payment request
- [ ] Payment request
### Popover
- [ ] Popover
### Select
- [ ] Select default 
- [ ] Select fees
### Spinner
- [ ] Spinner
### Transaction
- [ ] Transaction confirmed
- [ ] Transaction pending
### Forms
- [ ] Login form
- [ ] Wallet form
### Wrapper
- [ ] Wrapper

**Comment by kengork** [comment]
(∩ ͡° ͜ʖ ͡°)⊃━☆ﾟ. * ･ ｡ﾟ,

**Comment by Tommytrg** [comment]
This epic is part of the definition of done of #572 issues and will be completed at the same time.
