### ISSUE TITLE
Component stories

### ISSUE THREAD

**Issue by Tommytrg** [witnet/sheikah#572]
List of components that need a unit test.
### Alert
- [ ] Alert default
- [ ] Alert message
### Balance
- [ ] Balance
### Bars
- [ ] Sidebar
- [ ] Topbar
### Button
- [x] Button action
- [ ] Button default
- [ ] Button link
- [ ] Button navigation
- [ ] Button option
### Card
- [ ] Card default
- [ ] Card marketplace product
- [ ] Card navigation
### Dot indicator
- [ ] Dot indicator
### Dropdown
- [ ] Dropdown bordered
- [ ] Dropdown default
### Empty state
- [ ] Empty state
### Generic message
- [ ] Generic message
### Input
- [ ] Input amount 
- [ ] Input big
- [ ] Input amount
- [ ] Input checkbox
- [ ] Input default
- [ ] Input switch
- [ ] Input underlined
### List
- [ ] List
### Loading modal
- [ ] Loading modal
### Payment request
- [ ] Payment request
### Popover
- [ ] Popover
### Select
- [ ] Select default 
- [ ] Select fees
### Spinner
- [ ] Spinner
### Transaction
- [ ] Transaction confirmed
- [ ] Transaction pending
### Forms
- [ ] Login form
- [ ] Wallet form
### Wrapper
- [ ] Wrapper

**Comment by tomas302** [comment]
Hello! I would like to contribute by writing some unit tests. How could I help?

**Comment by Tommytrg** [comment]
Hi @tomas302. Thank you for your interest in shiekah! Currently, we are working on #591 to have an instance of a component test. This week we will create the issues of this epic and you could pick one.

**Comment by tomas302** [comment]
I'll be watching the issues and seeing where I can contribute then. Glad to help!

**Comment by Tommytrg** [comment]
@tomas302 we are refactoring Sheikah so we are opening a lot of new issues. We would love that you start contributing to one. Feel free to ask me anything you want in an issues or in discord :smiley:

**Comment by Tommytrg** [comment]
This issue is deprecated with the new structure of Sheikah that starts with #608.
