### ISSUE TITLE
Implement sheikah basic components

### ISSUE THREAD

**Issue by Tommytrg** [witnet/sheikah#609]
We are implementing a new structure and tooling for _Sheikah_ and with these new changes, we are not using `antd` anymore. Which means that we have to implement the behavior that the current components have from the `antd` library. The list of components that we have to implement are:
- [ ] Alert
- [ ] Balance

<details open>
<summary>Button</summary>
<ul>
<li>[ ] Default</li>
<li>[ ] Link</li>
<li>[ ] Navigation</li>
<li> [ ] Option</li>
</ul>
</details>

<details open>
<summary>Card</summary>
<ul>
<li>[ ] Default</li>
<li>[ ] Marketplace</li>
<li>[ ] Navigation</li>
</ul>
</details>

- [ ] Dot indicator

<details open>
<summary>Dropdown</summary>
<ul>
<li>[ ] Bordered</li>
<li>[ ] Default</li>
</ul>
</details>

- [ ] EmptyState
- [ ] GenericMessage

<details open>
<summary>Input</summary>
<ul>
<li>[ ] Amount</li>
<li>[ ] Big</li>
<li>[ ] Checkbox</li>
<li> [ ] Default</li>
<li>[ ] Switch </li>
<li>[ ] Underlined </li>
</ul>
</details>

- [ ] Layout
- [ ] List
- [ ] Loading modal
- [ ] Payment request
- [ ] Popover
- [ ] Select
- [ ] Sidebar
- [ ] Spinner
- [ ] Topbar
- [ ] Transaction
- [ ] Not implemented message

It also seems a good time to rethink which ones are unnecessary or should be refactored.

**Comment by aesedepece** [comment]
This makes sense to me.

We should also have a meeting sometime soon to discuss porting the containers and the like. What about later today @Tommytrg @kengork + anyone else interested ?

**Comment by kengork** [comment]
Cool!
