### ISSUE TITLE
Migrate link button from legacy one

### ISSUE THREAD

**Issue by Tommytrg** [witnet/sheikah#611]
The LinkButton should be similar to this:
![pic-selected-190514-1730-39](https://user-images.githubusercontent.com/24905681/57710862-05f60480-766e-11e9-846d-066769c5d88f.png)

**Comment by Tommytrg** [comment]
Can @kengork add a new kind like _link_ in #610 that implements this component?

**Comment by kengork** [comment]
Sure!

**Comment by Tommytrg** [comment]
Closed by #686
