### ISSUE TITLE
Migrate topbar component from legacy one

### ISSUE THREAD

**Issue by Tommytrg** [witnet/sheikah#631]
We should have two kinds of bars: primary and secondary. These bars should be similar to:
### Primary
![pic-selected-190514-1640-03](https://user-images.githubusercontent.com/24905681/57707305-aeed3100-7667-11e9-9ee9-26004d8a1365.png)

### Secondary
![pic-selected-190514-1640-18](https://user-images.githubusercontent.com/24905681/57707200-7ea59280-7667-11e9-8df8-0db00888e37a.png)

**Comment by kengork** [comment]
#closed

**Comment by kengork** [comment]
close by be45c79ba122ebab34a3e8e2d5dceeb05ff4ee7e
