### ISSUE TITLE
Integrate vuex with the wallet api 

### ISSUE THREAD

**Issue by gabaldon** [witnet/sheikah#783]
We should integrate vuex with the wallet app.
- [x] Connect send transaction with the wallet 
- [x] Define wallet structure 
- [x] Handle create wallet / unlock wallet properly 
- [x] Show node status in the status indicator

**Comment by aesedepece** [comment]
@gabaldon @Tommytrg Is this "Just not yet" still?

**Comment by Tommytrg** [comment]
This issue was closed by #718 and #745
