### ISSUE TITLE
Fix repository history

### ISSUE THREAD

**Issue by mariocao** [witnet/sheikah#785]
Fix the `sheikah` repository in order to show past contributors.

**Comment by gabaldon** [comment]
The output of this discussion is the issue  #844

**Comment by mariocao** [comment]
Any update on this issue?

**Comment by Tommytrg** [comment]
@mariocao solved this issue and the current default branch is master instead of dev

**Comment by aesedepece** [comment]
:clap: :clap: :clap: :clap: :clap: :clap: :clap:
