### ISSUE TITLE
Marketplace assesment 

### ISSUE THREAD

**Issue by Tommytrg** [witnet/sheikah#802]

**Comment by aesedepece** [comment]
What's the scope of this?

**Comment by Tommytrg** [comment]
We thought this issue to define what should be the structure of the marketplace from the sheikah to the server that stores the data requests

**Comment by gabaldon** [comment]
Outputs:

- The first approach is to have a centralized Marketplace 
- The requirement for publishing a data request is to have it deployed first.
- No need for the authentication of users 
- A client for the Marketplace is going to be implemented in Sheikah
