### ISSUE TITLE
Use wallet subscribe to get transactions

### ISSUE THREAD

**Issue by gabaldon** [witnet/sheikah#872]
Create a method in `api.js` to create a subscription to be notified when a new transaction is added.

**Comment by Tommytrg** [comment]
Currently, wallet subscriptions are not working as expected. I think @mariocao  and @girazoki  are working on it.

**Comment by aesedepece** [comment]
Awesome, thanks for the clarification! :hugs:

**Comment by Tommytrg** [comment]
re #879

**Comment by aesedepece** [comment]
This is done!
