### ISSUE TITLE
Missing popover on "Welcome Back" screen

### ISSUE THREAD

**Issue by mariocao** [witnet/sheikah#875]
**Describe the bug**
On the "Welcome Back" screen there is a deactivated button/menu called "App Settings" that does not anything.

**To Reproduce**
1. Open Sheikah
2. Hover over "App Settings"
3. Nothing happens :)

**Expected behavior**
It should have a pop over with some functionality such as "Close Sheikah".

**Comment by Tommytrg** [comment]
Closed by #882
