### ISSUE TITLE
ci(travis): assess usage of circle and other CI solutions

### ISSUE THREAD

**Issue by aesedepece** [witnet/sheikah#88]
This issue arised during last sprint plan meeting, after discussing #77.

**Comment by anler** [comment]
After investigation, I think we should stick to Travis for the following reasons:

- free MacOS builds
- more concurrent jobs for free accounts
- build matrix out of the box

@aesedepece if you agree, I go on and add #90

**Comment by aesedepece** [comment]
OK to close and move on with #90 :+1:
