### ISSUE TITLE
Update Sheikah after wallet resynch

### ISSUE THREAD

**Issue by lrubiorod** [witnet/sheikah#883]
If Sheikah is connected to a wallet and the wallet is stopped. When wallet is working again and Sheikah is also reconnected with it. From now to the future, transactions will not be updated in Sheikah.

I dont know if maybe it continues disconnected with wallet but show SYNC and the green circle, or it is connected but it doesnt update transactions anymore.

If you relaunch electron, it works again

**Comment by Tommytrg** [comment]
#879 will fix this
