### ISSUE TITLE
ValidationError info

### ISSUE THREAD

**Issue by lrubiorod** [witnet/sheikah#884]
ValidationError should show more information about the error

**Comment by Tommytrg** [comment]
@lrubiorod Is this related with #876?

**Comment by lrubiorod** [comment]
> @lrubiorod Is this related with #876?

I am not sure about what kind of message he saw. In my case, I think the problem was that I didnt have enough wits to create a transaction, but only appear a message of ValidationError without no more information

**Comment by Tommytrg** [comment]
Closed by #892
