### ISSUE TITLE
build(yarn): bignum failing to build

### ISSUE THREAD

**Issue by kronolynx** [witnet/sheikah#92]
In node versions 7, 9 and 10 `bignum` is failing to build.

    The module '~/sheikah/node_modules/bignum/binding/bignum.node'

    was compiled against a different Node.js version using
    NODE_MODULE_VERSION 59. This version of Node.js requires
    NODE_MODULE_VERSION 64. Please try re-compiling or re-installing

**Comment by aesedepece** [comment]
@kronolynx Please explain here your solution :)
