### ISSUE TITLE
Error to install

### ISSUE THREAD

**Issue by wimel** [witnet/sheikah#931]
Installing, in the `yarn` step have the error:
```
yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
error default-gateway@5.0.5: The engine "node" is incompatible with this module. Expected version "^8.12.0 || >=9.7.0". Got "8.10.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Need to use a minmal version of node _(^8.12.0)_, installing (following the steps of the [repo of node](https://github.com/nodesource/distributions/blob/master/README.md#debinstall)) with:
```
curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -

sudo apt update

sudo apt-get install -y nodejs
```

`v13.9.0` of node works well, I don't test with others versions.

**Comment by Tommytrg** [comment]
Hi @wimel, thank you for your help. There is an open PR where we update the readme and it should be merged ASAP. Unfortunately, we can't add support for that Node.js version because the Vue CLI requires Node.js 8.9 or above (8.11.0+ recommended).

**Comment by wimel** [comment]
ok thanks @Tommytrg !!
