### ISSUE TITLE
Transaction details assessment

### ISSUE THREAD

**Issue by Tommytrg** [witnet/sheikah#960]
Discuss what information sheikah needs from the wallet to show.

**Comment by Tommytrg** [comment]
Ideally, a transaction detail should show the following information:
- Amount in nanowits.
- Transaction type.
- Transaction inputs.
- Transaction outputs.
- Transaction status.
- Transaction fees.
- Activity history
- Specific transaction type information,

According to that, the structure of transaction details depends of the transaction type:
#### VTTransaction: 
```
type VTTransaction = {
    type: 'vtt'
    amount: String
    id: String
    inputs: Array<String>
    outputs: Array<String>
    status: 'pending' | 'confirmed'
    fee: String
    creation_date: Date
    confirmation_date: Date | null
    label: String
}
```

#### DRTransaction
```
{
    type: 'dr'
    fee String
    id: String
    inputs: Array<String>
    outputs: Array<String>
    data_request: String
    reveal_transaction: String
    commit_transaction: String
    status: 'pending' | 'confirmed'
    tally_transaction: String
    creation_date: Date,
    confirmation_date: Date
}
```

#### CommitTransaction
```
{
    type: 'commit'
    fee: String
    id: String
    inputs: Array<String>
    outputs: Array<String>
    reveal_transaction: String
    data_request_transaction: String
    status: " "
    tally_transaction: String
    creation_date: Date,
    confirmation_date: Date
}
```
#### RevelTransaction
```
{
    type: 'reveal'
    fee: String
    id: String
    inputs: Array<String>
    outputs: Array<String>
    commit_transaction: String
    data_request_transaction: String
    status: 'pending' | 'confirmed'
    tally_transaction: String
    creation_date: Date,
    confirmation_date: Date
}
```

#### TallyTransaction
```
{
    type: 'tally'
    fee: String
    id: String
    inputs: Array<String>
    outputs: Array<String>
    data_request_transaction: String
    commit_transaction: String
    reveal_transaction: String
    status: 'pending' | 'confirmed'
    creation_date: Date,
    confirmation_date: Date
}
```

#### MintTransaction
```
{
    type: 'mint'
    id: String
    outputs: Array<String>
    status: 'pending' | 'confirmed'
    creation_date: Date,
    confirmation_date: Date
}
```
What do you think? @witnet/devs

**Comment by tmpolaczyk** [comment]
Do we want to eventually support all the different types of transactions? If so, at which level?

For example: selecting a `DataRequestTransaction` should show information about the status of the data request, all the commits, all the reveals, and the result, aside from the data request itself with all its scripts or whatever.

Or do we want to simply index the +/- in balance and show the transaction type as a small detail, meaning that all the types of transactions will have the same look and feel, and for example data request transactions will only show the total cost.

**Comment by mariocao** [comment]
> Ideally, a transaction detail should show the following information:
> 
> * Amount in nanowits.
> * Transaction type.
> * Transaction inputs.
> * Transaction outputs.
> * Transaction status.
> * Transaction fees.
> * **~Activity history.~**

I prefer `timestamp`. I propose to be the creation date for `pending` transactions and confirmation date for `confirmed` transactions.

> * Specific transaction type information,
> 
> According to that, the structure of transaction details depends of the transaction type:
> 
> #### VTTransaction:
> ```
> {
>     type: 'vtt'
>     amount: String
>     id: String
>     inputs: Array<String>
>     outputs: Array<String>
>     status: 'pending' | 'confirmed'
>     fee: String
>     creation_date: Date
>     confirmation_date: Date | null
> ```

As mentioned above, `timestamp` for both `creation_date` and `confirmation_date`. It applies to other transactions too.

>```
>     label: String
> ```

Right now, labels are retrieved by Sheikah.

> ```
> }
> ```
> 
> #### DRTransaction
> ```
> {
>     type: 'dr'
>     fee: String
>     id: String
>     inputs: Array<String>
>     outputs: Array<String>
>     data_request: String
>     reveal_transaction: String
>     commit_transaction: String
>     status: 'pending' | 'confirmed'
>     tally_transaction: String
>     creation_date: Date,
>     confirmation_date: Date
> }
> ```
> 
> #### CommitTransaction
> ```
> {
>     type: 'commit'
>     fee: String
>     id: String
>     inputs: Array<String>
>     outputs: Array<String>
>     reveal_transaction: String
>     data_request_transaction: String
>     status: " "
>```

Doesn't make sense, they will always be `confirmed` if wallet indexes them. It also applies to `RevealTransaction`, `TallyTransaction` and `MintTransaction`.

**Comment by Tommytrg** [comment]
The result of the discussion is:
#### VTTransaction: 
```
{
    type: 'vtt',
    amount: String,
    id: String,
    inputs: Array<Input>,
    outputs: Array<Output>,
    status: 'pending' | 'confirmed',
    fee: String,
    timestamp: Number | null,
}
```

#### DRTransaction
```
{
    type: 'dr',
    fee: String,
    id: String,
    inputs: Array<Input>,
    outputs: Array<Outputs>,
    data_request: String,
    status: 'pending' | 'confirmed',
    timestamp: Number,
}
```

#### TallyTransaction
```
{
    type: 'tally',
    fee: String,
    id: String,
    outputs: Array<Outputs>,
    timestamp: Number,
    tally: String,
    data_request_transaction: String,
}
```

#### MintTransaction
```
{
    type: 'mint',
    id: String,
    outputs: Array<String>,
    timestamp: Number,
}
```

**Comment by aesedepece** [comment]
Just in case we consider giving this API a balance movement focused approach at some point in the future:

### Balance movement
```ts
{
    type: "positive" | "negative",
    amount: Number,
    transaction: {
        hash: String,
        timestamp: Number,
        block: String | void, // Replaces `status`
        data: VtData | DrData | TData
    }
}
```

### VtData
```ts
{
    inputs: Array<Input>,
    outputs: Array<Output>,
}
```

### DrData
```ts
{
    inputs: Array<Input>,
    outputs: Array<Output>,
    tally: TallyReport | void
}
```

### TtData
```ts
{
    request_transaction_hash: String,
    outputs: Array<Output>,
    tally: TallyReport
}
```

### TallyReport
```ts
{
    result: String // Actually RadonType
    reveals: Array<Reveal>
}
```

### Reveal
```ts

**Comment by Tommytrg** [comment]
> Do we want to eventually support all the different types of transactions? If so, at which level?
> 
> For example: selecting a `DataRequestTransaction` should show information about the status of the data request, all the commits, all the reveals, and the result, aside from the data request itself with all its scripts or whatever.
> 
> Or do we want to simply index the +/- in balance and show the transaction type as a small detail, meaning that all the types of transactions will have the same look and feel, and for example data request transactions will only show the total cost.

This issue aims to have a structure for mainnet.

**Comment by aesedepece** [comment]
Just in case we consider giving this API a balance movement focused approach at some point in the future:

### Balance movement
```ts
{
    type: "positive" | "negative",
    amount: Number,
    timelock: Number,
    transaction: {
        hash: String,
        timestamp: Number,
        block: Beacon | void, // replaces `status`
        miner_fee: Number,
        data: VtData | DrData | TData
    }
}
```

### Beacon
```ts
{
    epoch: Number,
    block_hash: String
}
```

### VtData
```ts
{
    inputs: Array<Input>,
    outputs: Array<Output>,
}
```

### DrData
```ts
{
    inputs: Array<Input>,
    outputs: Array<Output>,
    tally: TallyReport | void
}
```

### TtData
```ts
{
    request_transaction_hash: String,
    outputs: Array<Output>,
    tally: TallyReport
}
```

### TallyReport
```ts
{
    result: String // Actually RadonType | RadonError, aka RadonReport
    reveals: Array<Reveal>
}
```

### Reveal
```ts
{
    value: String // Actually RadonType,
    in_consensus: Boolean
}
```

**Comment by Tommytrg** [comment]
This issue can be close since we have a structure defined
