### ISSUE TITLE
Add disclaimer steps in claiming flow

### ISSUE THREAD

**Issue by Tommytrg** [witnet/sheikah#964]
Disccuss and implement the disclaimers that need to be shown in the claiming process flow. We have to show a compact title and below show all the information offering the possibility of "view more"

**Comment by Tommytrg** [comment]
First proposal for disclaimer component:
![image](https://user-images.githubusercontent.com/24905681/77159017-ce819100-6aa4-11ea-8429-f497c4020352.png)
 What do you think @witnet/devs

**Comment by tmpolaczyk** [comment]
I think this lacks the "important" feel, maybe add a red triangle or a solid color border or something.

**Comment by Tommytrg** [comment]
This PR is partially closed with #1003 and the remaining is overlapped with #1002
