### ISSUE TITLE
Create a step to show whether a user has generated the addresses

### ISSUE THREAD

**Issue by gabaldon** [witnet/sheikah#974]
Save in wallet key-value whether a user has generated the addresses.

**Comment by Tommytrg** [comment]
What would happen if users create a wallet but they don't wait until their addresses are generated? @gabaldon @aesedepece

**Comment by aesedepece** [comment]
I wouldn't write the confirmation into the storage until complete. In that
way, if you cancel at any time before finishing, you must start anew.

**Comment by Tommytrg** [comment]
This issue can be close because we don't need anymore a step between generate addresses and create wallet. If you don't complete the process you will have to start it from the beginning.
