### ISSUE TITLE
Generate addresses according to the number of wits

### ISSUE THREAD

**Issue by Tommytrg** [witnet/sheikah#987]
We have to generate addresses according to the number of wits that the imported file contains.
To do that, we have to distribute wits in addresses that will contains multiples of 5 * 10^n.
For instance: 5558 wits will be distributed as follows:
1. 5000
2. 500
3. 50
4. 5
6. 3

**Comment by aesedepece** [comment]
For convenience and deniability, we may decide to round up to `50` or `500`. `5558` in your example would become `5600` or `6000`.
