### ISSUE TITLE
Define and implement claiming export file format 

### ISSUE THREAD

**Issue by Tommytrg** [witnet/sheikah#994]
Define the structure of the file that will be sent to the witnet foundation after complete the claiming process in Sheikah.

**Comment by Tommytrg** [comment]
### Output
The output format of the generated claiming file is:
```ts
type File = {
    email_address: String
    name: String
    addresses: Array<{ pkh: String, amount: Number }>
    disclaimers: {
        disclaimer_name_1: String // signature      
        disclaimer_name_2: String      
        disclaimer_name_n: String  
    }
    signature: String
}
```

**Comment by aesedepece** [comment]
STOP CALLING ADDRESSES AS PKH :rofl:

**Comment by Tommytrg** [comment]
> STOP CALLING ADDRESSES AS PKH rofl

Fix it

**Comment by tmpolaczyk** [comment]
`timelock` should be a UNIX timestamp, serialized as a `Number` and not as a `Date`

**Comment by tmpolaczyk** [comment]
In `genesis_block.json` the field names are `address`, `value`, and `timelock`. Can we rename `amount` to `value` for consistency? Note: that number should be in nanowits.
